threat( pose [ -7.65 7.65 0 0 ] size [ 0.7 0.7 0 ] prob 0.01 color "red") # upper-left corner
threat( pose [ -7 6.35 0 0 ] size [ 2 0.7 0 ] prob 0.01 color "red")
threat( pose [ 6.5 7.25 0 0 ] size [ 3 1.5 0 ] prob 0.01 color "red") # upper-right corner
threat( pose [ 7.5 5.5 0 0 ] size [ 1 2 0 ] prob 0.01 color "red")
threat( pose [ 3 4 0 0 ] size [ 1 1.5 0 ] prob 0.01 color "red")
threat( pose [ 7 2 0 0 ] size [ 1.5 1 0 ] prob 0.01 color "red")
threat( pose [ -2 2 0 0 ] size [ 1.8 1 0 ] prob 0.01 color "red")
threat( pose [ -5 0.8 0 0 ] size [ 3 1.5 0 ] prob 0.01 color "red")
threat( pose [ -4.5 -6 0 0 ] size [ 4 2 0 ] prob 0.01 color "red")
threat( pose [ 1.85 -1.5 0 0 ] size [ 0.8 1.8 0 ] prob 0.01 color "red") # upper bridge
threat( pose [ 0 -6.15 0 0 ] size [ 0.5 3.6 0 ] prob 0.01 color "red") # lower bridge
threat( pose [ 6 -3 0 0 ] size [ 1.5 1.5 0 ] prob 0.01 color "red")
threat( pose [ 0 6.62 0 0 ] size [ 1.4 0.6 0 ] prob 0.01 color "red")
